import 'dart:io';

import 'package:path/path.dart' as p;

import '../dart_literal.dart';
import '../fonts/font_cache.dart';
import '../scan/candidate.dart';
import 'design.dart';
import 'engine.dart';
import 'harness_text.dart';

/// File header of every generated Dart file: the code is machine
/// written from the project's own sources, so lints do not apply.
const generatedHeader =
    '// GENERATED by shutter. Do not edit; `shutter shot` rewrites this '
    'file.\n'
    '// ignore_for_file: type=lint, unused_import, unnecessary_import, '
    'duplicate_import, implementation_imports, '
    'invalid_use_of_visible_for_testing_member, '
    'invalid_use_of_internal_member, deprecated_member_use, '
    'depend_on_referenced_packages, undefined_hidden_name\n';

/// Settings baked into the generated test.
class const GeneratorConfig({
  required final CaptureRequest request,

  /// Where the Flutter SDK caches Roboto and MaterialIcons.
  required final String materialFontsDir,

  /// Design libraries for the default shell and the theme font fallback.
  required final DesignSupport design,

  /// The project depends on google_fonts.
  required final bool googleFonts,

  /// Cached google_fonts files to register and serve as assets.
  required final List<CachedFont> fonts,
});

/// Name of the helper library shooting [CaptureRequest.widget].
const widgetHelper = 'widget';

/// Writes `.dart_tool/shutter/test/<run-id>/`: the harness, the design library
/// adapters, one helper library per source library (and one for the
/// `--widget`), and `shutter_test.dart` tying them together. Each run has
/// its own directory, so concurrent shots do not overwrite each other's
/// code.
/// Candidates with an [Candidate.error] are left out.
///
/// Returns the path of `shutter_test.dart`.
String writeGeneratedTest(GeneratorConfig config) {
  final request = config.request;
  final dir = p.join(request.project.testDir, p.basename(request.runDir));
  if (Directory(dir).existsSync()) Directory(dir).deleteSync(recursive: true);
  Directory(p.join(dir, 'sources')).createSync(recursive: true);
  File(p.join(dir, 'shutter_harness.dart')).writeAsStringSync(harnessText);
  File(p.join(dir, 'shutter_design.dart'))
      .writeAsStringSync(designSource(config.design));

  final helpers = <String>[];
  for (final (i, library) in request.libraries.indexed) {
    final source = helperSource(library);
    if (source == null) continue;
    File(p.join(dir, 'sources', 'l$i.dart')).writeAsStringSync(source);
    helpers.add('l$i');
  }
  if (request.widget case final widget?) {
    File(p.join(dir, 'sources', '$widgetHelper.dart'))
        .writeAsStringSync(widget.helperSource());
    helpers.add(widgetHelper);
  }

  final testPath = p.join(dir, 'shutter_test.dart');
  File(testPath).writeAsStringSync(mainSource(helpers, config));
  return testPath;
}

/// Source of the helper library for [library]: the prefixed imports its
/// candidates reach names through, and `entries()`. Null when no
/// candidate can be shot.
String? helperSource(SourceLibrary library) {
  final candidates = [
    for (final c in library.candidates)
      if (c.error == null) c,
  ];
  if (candidates.isEmpty) return null;
  return helperLibrary(
    source: library.file,
    imports: library.imports,
    entries: [
      for (final c in candidates)
        {
          'id': "'${c.staticId}'",
          'file': dartString(c.file),
          'line': '${c.line}',
          'symbol': dartString(c.symbol),
          'annotation': '() => ${c.annotation}',
          'target': c.target,
        },
    ],
  );
}

/// A helper library generated from [source]: [imports], the harness, and
/// `entries()` returning one `ShutterEntry` per map of named arguments.
String helperLibrary({
  required String source,
  required List<String> imports,
  required List<Map<String, String>> entries,
}) {
  final buffer = StringBuffer(generatedHeader)
    ..writeln('// Source: $source')
    ..writeln()
    // A prefixed `dart:core` import among [imports] hides the implicit
    // one, which the code below relies on.
    ..writeln("import 'dart:core';");
  imports.forEach(buffer.writeln);
  buffer
    ..writeln(r"import '../shutter_harness.dart' as $shutter;")
    ..writeln()
    ..writeln(r'List<$shutter.ShutterEntry> entries() => [');
  for (final entry in entries) {
    buffer.writeln(r'  $shutter.ShutterEntry(');
    for (final MapEntry(:key, :value) in entry.entries) {
      buffer.writeln('    $key: $value,');
    }
    buffer.writeln('  ),');
  }
  buffer.writeln('];');
  return buffer.toString();
}

/// Source of `shutter_test.dart`.
String mainSource(List<String> helpers, GeneratorConfig config) {
  final request = config.request;
  final project = request.project;
  final shell = request.shell;
  final buffer = StringBuffer(generatedHeader)..writeln();
  if (shell != null) {
    // A shell outside lib/ (say under .dart_tool/) has no package: URI.
    final uri = p.isWithin(project.libDir, shell)
        ? project.packageUri(shell)
        : Uri.file(shell).toString();
    buffer.writeln("import '$uri' as \$shell;");
  }
  buffer
    ..writeln(r"import 'shutter_design.dart' as $design;")
    ..writeln(r"import 'shutter_harness.dart' as $shutter;");
  for (final (i, helper) in helpers.indexed) {
    buffer.writeln("import 'sources/$helper.dart' as \$s$i;");
  }
  buffer
    ..writeln()
    ..writeln('void main() {')
    ..writeln(r'  $shutter.run(')
    ..writeln(r'    config: const $shutter.ShutterConfig(')
    ..writeln('      runDir: ${dartString(request.runDir)},')
    ..writeln('      projectRoot: ${dartString(project.root)},')
    ..writeln('      packageName: ${dartString(project.name)},')
    ..writeln('      materialFontsDir: ${dartString(config.materialFontsDir)},')
    ..writeln('      settleMs: ${request.settleMs},')
    ..writeln('      googleFonts: ${config.googleFonts},');
  if (request.actions.isNotEmpty) {
    buffer.writeln('      actions: [');
    for (final action in request.actions) {
      buffer.writeln('        ${action.source},');
    }
    buffer.writeln('      ],');
  }
  if (request.screen) buffer.writeln('      screen: true,');
  if (request.viewport case (final width, final height)?) {
    buffer.writeln('      viewport: ($width, $height),');
  }
  buffer
    ..writeln('    ),')
    ..writeln(r'    defaultShell: $design.defaultShell,')
    ..writeln(r'    themeFallback: $design.themeFallback,');
  if (shell != null) buffer.writeln(r'    shell: $shell.shell,');
  if (config.fonts.isNotEmpty) {
    buffer.writeln('    fonts: [');
    for (final cached in config.fonts) {
      buffer
        ..writeln(r'      $shutter.ShutterFont(')
        ..writeln(
          '        family: ${dartString(cached.font.registeredFamily)},',
        )
        ..writeln('        asset: ${dartString(cached.font.assetName)},')
        ..writeln('        path: ${dartString(cached.path)},')
        ..writeln('      ),');
    }
    buffer.writeln('    ],');
  }
  buffer.writeln('    entries: [');
  for (var i = 0; i < helpers.length; i++) {
    buffer.writeln('      ...\$s$i.entries(),');
  }
  buffer
    ..writeln('    ],')
    ..writeln('  );')
    ..writeln('}');
  return buffer.toString();
}
