/// Source of `.shutter/test/<run-id>/shutter_harness.dart`, the runtime
/// half of the `flutter_test` engine. It is plain Flutter test code: it
/// depends on `flutter` and `flutter_test` only, so the target project
/// gains no dependency on shutter. The generated `shutter_test.dart` calls [run]
/// with the scanned entries; each preview becomes one `testWidgets` that
/// writes `<run>/<id>.png` and `<run>/.results/<id>.json`.
///
/// The end-to-end tests under `test/e2e/` compile and run this text
/// against `example/`.
const String harnessText = r'''
// GENERATED by shutter. Do not edit; `shutter shot` rewrites this file.
// ignore_for_file: type=lint, implementation_imports, invalid_use_of_visible_for_testing_member, deprecated_member_use

import 'dart:convert';
import 'dart:io';
import 'dart:ui' as ui;

import 'package:flutter/foundation.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/services.dart';
import 'package:flutter/widget_previews.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';

/// Run-wide settings written by the shutter CLI.
class const ShutterConfig({
  required final String runDir,
  required final String projectRoot,
  required final String packageName,

  /// Where the Flutter SDK caches Roboto and MaterialIcons.
  required final String materialFontsDir,
  required final int settleMs,

  /// The project depends on google_fonts.
  required final bool googleFonts,
});

/// A google_fonts file cached by the CLI.
class const ShutterFont({
  /// Family name google_fonts registers (`Lobster_regular`).
  required final String family,

  /// File name google_fonts looks for among assets (`Lobster-Regular.ttf`).
  required final String asset,

  /// The cached file.
  required final String path,
});

/// One annotated declaration, as found by the shutter scanner, or the
/// `--widget` expression (no file, line, or symbol).
class const ShutterEntry({
  required final String id,
  final String? file,
  final int? line,
  final String? symbol,
  required final Object? Function() annotation,
  required final Function target,
});

/// google_fonts' failure messages: a fetched file (by hash), or, with
/// `GoogleFonts.config.allowRuntimeFetching = false`, an asset it looked
/// for (by `<Family>-<Variant>` file name prefix).
final _missingFont = RegExp(r'fonts\.gstatic\.com/s/a/([0-9a-f]{64})\.ttf');
final _missingAsset = RegExp(
  r'font (\S+) was not found in the application assets',
);

/// Device pixel ratio every shot is rendered at.
const double _pixelRatio = 2;

/// Logical viewport used when a preview does not fix a dimension.
const Size _fallbackViewport = Size(800, 600);

const Duration _precacheTimeout = Duration(seconds: 5);

void run({
  required ShutterConfig config,
  required List<ShutterEntry> entries,
  required Widget Function(Widget) defaultShell,
  required Widget Function(BuildContext, Widget, List<String>) themeFallback,
  Widget Function(Widget)? shell,
  List<ShutterFont> fonts = const [],
}) {
  TestWidgetsFlutterBinding.ensureInitialized();
  _defaultShell = defaultShell;
  _themeFallback = themeFallback;
  _location = RegExp(
    '(?:${RegExp.escape(Uri.directory(config.projectRoot).toString())}lib/'
    '|package:${RegExp.escape(config.packageName)}/)'
    r'([^\s:)]+\.dart):(\d+)(?::(\d+))?',
  );
  Directory('${config.runDir}/.results').createSync(recursive: true);
  if (config.googleFonts) _prepareGoogleFonts(fonts);
  setUpAll(() => _loadFonts(config.materialFontsDir, fonts));
  for (final entry in entries) {
    final List<Preview> previews;
    try {
      final annotation = entry.annotation();
      previews = annotation is Preview
          ? [annotation.transform()]
          : (annotation as MultiPreview).transform();
    } catch (error, stack) {
      // The preview's name is unknown; the shot is named after the symbol.
      final id = '${entry.id}.0';
      final name = entry.symbol ?? id;
      test(id, () {
        _writeResult(config, {
          ..._entryFields(entry, id, name),
          'status': 'error',
          ..._errorFields(
            entry,
            FlutterErrorDetails(exception: error, stack: stack),
          ),
        });
      });
      continue;
    }
    for (var i = 0; i < previews.length; i++) {
      final preview = previews[i];
      final id = '${entry.id}.$i';
      final name = preview.name ?? entry.symbol ?? id;
      // Stands in for the result when the test never writes one (timeout,
      // a crash, or the test process exiting).
      _writeResult(config, {
        ..._entryFields(entry, id, name),
        'status': 'error',
        'error': 'no result: the shot timed out, or the test process '
            'stopped before it finished',
        ..._entryAt(entry),
      }, planned: true);
      testWidgets(
        id,
        (tester) => _capture(tester, config, entry, preview, id, name, shell),
        timeout: const Timeout(Duration(minutes: 2)),
      );
    }
  }
}

Map<String, Object?> _entryFields(
  ShutterEntry entry,
  String id,
  String name,
) => {
  'id': id,
  'name': name,
  if (entry.file != null) 'file': entry.file,
  if (entry.line != null) 'line': entry.line,
};

/// `at` pointing at the declaration; none for an expression.
Map<String, Object?> _entryAt(ShutterEntry entry) => {
  if (entry.file != null) 'at': '${entry.file}:${entry.line}',
};

Future<void> _capture(
  WidgetTester tester,
  ShutterConfig config,
  ShutterEntry entry,
  Preview preview,
  String id,
  String name,
  Widget Function(Widget)? shell,
) async {
  addTearDown(tester.view.reset);
  addTearDown(tester.platformDispatcher.clearAllTestValues);
  // Described while the tree is still mounted: the "relevant
  // error-causing widget" location is looked up through live elements.
  Map<String, Object?>? firstError;
  // Every google_fonts file that failed to load, not just the first
  // error's: the CLI downloads them all before shooting again.
  final missingFonts = <String>{};
  bool noteMissingFonts(String text) {
    final before = missingFonts.length;
    missingFonts
      ..addAll(_missingFont.allMatches(text).map((match) => match.group(1)!))
      ..addAll(_missingAsset.allMatches(text).map((match) => match.group(1)!));
    return missingFonts.length > before;
  }

  // flutter_test paints an elevation as a solid outline in place of its
  // shadow; a device paints the shadow. The binding checks the flag is
  // restored when the test ends.
  final previousShadows = debugDisableShadows;
  debugDisableShadows = false;
  final previous = FlutterError.onError;
  FlutterError.onError = (details) {
    firstError ??= _errorFields(entry, details);
    noteMissingFonts(details.exceptionAsString());
    previous?.call(details);
  };
  // google_fonts 8.2 and later report a font that fails to load only
  // through debugPrint; the text is still drawn, in another font. Its
  // public GoogleFonts.pendingFonts() cannot tell: under flutter_test the
  // load fails within the first pumpWidget and a failed load leaves the
  // pending set when it completes.
  final previousPrint = debugPrint;
  debugPrint = (message, {wrapWidth}) {
    if (message != null && noteMissingFonts(message)) {
      firstError ??= {
        'error': message.split('\n').first.replaceFirst('Error: ', ''),
        ..._entryAt(entry),
      };
    }
    previousPrint(message, wrapWidth: wrapWidth);
  };
  final result = <String, Object?>{
    ..._entryFields(entry, id, name),
    if (preview.brightness != null) 'brightness': preview.brightness!.name,
    if (preview.textScaleFactor != null)
      'text_scale_factor': preview.textScaleFactor,
  };
  LocalizationsResolver? resolver;
  try {
    final size = preview.size;
    final width = size != null && size.width.isFinite ? size.width : null;
    final height = size != null && size.height.isFinite ? size.height : null;
    final viewport = Size(
      width ?? _fallbackViewport.width,
      height ?? _fallbackViewport.height,
    );
    tester.view.devicePixelRatio = _pixelRatio;
    tester.view.physicalSize = viewport * _pixelRatio;
    if (preview.brightness != null) {
      tester.platformDispatcher.platformBrightnessTestValue =
          preview.brightness!;
    }
    if (preview.textScaleFactor != null) {
      tester.platformDispatcher.textScaleFactorTestValue =
          preview.textScaleFactor!;
    }

    Widget child = _subject(entry);
    final wrapper = preview.wrapper;
    if (wrapper != null) child = wrapper(child);
    final theme = preview.theme;
    if (theme != null) {
      final inner = _withFallbackFonts(child);
      child = Builder(builder: (context) => theme().apply(context, inner));
    }
    final key = GlobalKey();
    child = RepaintBoundary(
      key: key,
      child: SizedBox(width: width, height: height, child: child),
    );
    // Without a finite height the preview gets unbounded height, as in a
    // scrolling list, and is shot at its own height; the width stays
    // bounded by the viewport, as on a screen.
    child = _withFallbackFonts(
      OverflowBox(
        alignment: Alignment.topLeft,
        minWidth: 0,
        minHeight: 0,
        maxHeight: double.infinity,
        child: child,
      ),
    );
    final localizations = preview.localizations;
    if (localizations != null) {
      final data = localizations();
      final r = resolver = LocalizationsResolver(
        supportedLocales: data.supportedLocales,
        locale: data.locale,
        localeListResolutionCallback: data.localeListResolutionCallback,
        localeResolutionCallback: data.localeResolutionCallback,
        localizationsDelegates: data.localizationsDelegates,
      );
      child = Localizations(
        locale: r.locale,
        delegates: r.localizationsDelegates.toList(),
        child: child,
      );
    }
    child = ((wrapper == null ? shell : null) ?? _defaultShell)(child);

    await tester.pumpWidget(child);
    await _precacheImages(tester);
    await tester.pump(Duration(milliseconds: config.settleMs));

    final boundary = key.currentContext?.findRenderObject();
    if (boundary is RenderRepaintBoundary && !boundary.debugNeedsPaint) {
      final image = boundary.toImageSync(pixelRatio: _pixelRatio);
      final bytes = await tester.runAsync(
        () => image.toByteData(format: ui.ImageByteFormat.png),
      );
      image.dispose();
      if (bytes != null) {
        final png = '$id.png';
        File('${config.runDir}/$png').writeAsBytesSync(
          bytes.buffer.asUint8List(bytes.offsetInBytes, bytes.lengthInBytes),
        );
        result['png'] = png;
        result['size'] = [
          _round(boundary.size.width),
          _round(boundary.size.height),
        ];
      }
    }
  } catch (error, stack) {
    firstError ??= _errorFields(
      entry,
      FlutterErrorDetails(exception: error, stack: stack),
    );
  } finally {
    FlutterError.onError = previous;
    debugPrint = previousPrint;
    debugDisableShadows = previousShadows;
  }
  try {
    await tester.pumpWidget(const SizedBox.shrink());
  } catch (_) {}
  resolver?.dispose();
  while (tester.takeException() != null) {}
  if (missingFonts.isNotEmpty) result['missing_fonts'] = [...missingFonts];
  if (firstError == null && result['png'] == null) {
    firstError = {
      'error': 'nothing was painted: the preview is not in the painted '
          'tree (does the shell or wrapper build its child?)',
      ..._entryAt(entry),
    };
  }
  if (firstError case final error?) {
    result['status'] = 'error';
    result.addAll(error);
  } else {
    result['status'] = 'ok';
  }
  _writeResult(config, result);
}

/// Two decimals: enough to read, stable against float noise.
double _round(double value) => (value * 100).roundToDouble() / 100;

Widget _subject(ShutterEntry entry) {
  final built = Function.apply(entry.target, const []);
  if (built is Widget) return built;
  if (built is WidgetBuilder) return Builder(builder: built);
  throw StateError(
    '${entry.symbol ?? 'the expression'} returned ${built.runtimeType}; '
    'a preview must return a Widget or a WidgetBuilder.',
  );
}

Future<void> _precacheImages(WidgetTester tester) async {
  final images = find.byType(Image, skipOffstage: false).evaluate().toList();
  if (images.isEmpty) return;
  await tester.runAsync(() async {
    await Future.wait([
      for (final element in images)
        precacheImage((element.widget as Image).image, element)
            .timeout(_precacheTimeout, onTimeout: () {}),
    ]);
  });
  await tester.pump();
}

/// The first line of the error, and `at`: the first `lib/` location in its
/// report, else the failing `Image`'s, else the preview's own (none for an
/// expression).
Map<String, Object?> _errorFields(
  ShutterEntry entry,
  FlutterErrorDetails details,
) {
  final message = details
      .exceptionAsString()
      .split('\n')
      .map((line) => line.trim())
      .firstWhere((line) => line.isNotEmpty, orElse: () => 'unknown error');
  final at =
      _locate('${details.toString()}\n${details.stack ?? ''}') ??
      _imageLocation(details);
  return {
    'error': message,
    if (at != null) 'at': at else ..._entryAt(entry),
  };
}

/// Image load errors carry the failing `ImageProvider` but no widget
/// location. Finds the mounted `Image` showing that provider and reads
/// its creation location the way the framework does for layout errors.
String? _imageLocation(FlutterErrorDetails details) {
  final providers = [
    for (final node in details.informationCollector?.call() ??
            const <DiagnosticsNode>[])
      if (node.value case final ImageProvider<Object> provider) provider,
  ];
  if (providers.isEmpty) return null;
  Element? found;
  void visit(Element element) {
    if (found != null) return;
    final widget = element.widget;
    if (widget is Image && providers.contains(widget.image)) {
      found = element;
      return;
    }
    element.visitChildren(visit);
  }

  WidgetsBinding.instance.rootElement?.visitChildren(visit);
  final element = found;
  if (element == null) return null;
  final described = FlutterErrorDetails(
    exception: '',
    informationCollector: () => [
      DiagnosticsDebugCreator(DebugCreator(element)),
    ],
  ).toString();
  return _locate(described);
}

/// A `lib/` file of the project, as a file or `package:` URI, with its
/// line and column. Set by [run].
late final RegExp _location;

/// First `lib/...:line:column` of the project named in [text]. Generated
/// code under `.shutter/` never counts.
String? _locate(String text) {
  final match = _location.firstMatch(text);
  if (match == null) return null;
  final path = 'lib/${match.group(1)!}';
  final column = match.group(3);
  return column == null
      ? '$path:${match.group(2)}'
      : '$path:${match.group(2)}:$column';
}

/// Writes `<id>.json`, or with [planned] the `<id>.planned` placeholder
/// the CLI reports when `<id>.json` never appears.
void _writeResult(
  ShutterConfig config,
  Map<String, Object?> result, {
  bool planned = false,
}) {
  File(
    '${config.runDir}/.results/${result['id']}.${planned ? 'planned' : 'json'}',
  ).writeAsStringSync(jsonEncode(result));
}

/// The shell used when the project has none, and for previews with their
/// own `wrapper`. Written by the CLI for the design library the project
/// depends on (`shutter_design.dart`).
late Widget Function(Widget) _defaultShell;

/// Adds the fallback families to the text themes of every design library
/// whose theme the shell provides. Written by the CLI with [_defaultShell].
late Widget Function(BuildContext, Widget, List<String>) _themeFallback;

/// Families registered from system fonts in [_loadFonts]; appended as
/// `fontFamilyFallback` to the default text style and the text themes.
final _fallbackFamilies = <String>[];

/// The flutter_test engine does no system font fallback: a glyph missing
/// from the style's families renders as a box. Real devices fall back to
/// system CJK and emoji fonts, so the same fonts are loaded from the host
/// and added to the fallback list of the ambient default text style, and
/// of the design libraries' text themes the shell provides. A shell
/// without a design library gets none from this.
Widget _withFallbackFonts(Widget child) {
  if (_fallbackFamilies.isEmpty) return child;
  return Builder(
    builder: (context) => _themeFallback(
      context,
      // Theme widgets insert an IconTheme of their own; the shell's is
      // restored inside them.
      IconTheme(
        data: IconTheme.of(context),
        child: DefaultTextStyle.merge(
          style: TextStyle(fontFamilyFallback: _fallbackFamilies),
          child: child,
        ),
      ),
      _fallbackFamilies,
    ),
  );
}

/// Host fonts covering CJK and emoji, by fallback family.
Map<String, List<File>> _systemFallbackFonts() {
  final cjk = <File>[];
  final emoji = <File>[];
  List<File> files(String dir) {
    final directory = Directory(dir);
    if (!directory.existsSync()) return const [];
    try {
      return directory
          .listSync(recursive: true, followLinks: false)
          .whereType<File>()
          .toList();
    } on FileSystemException {
      return const [];
    }
  }

  // Exact paths rather than directory listings: macOS returns
  // decomposed (NFD) Japanese file names, which never equal a literal.
  List<File> existing(List<String> paths) => [
    for (final path in paths)
      if (File(path).existsSync()) File(path),
  ];
  if (Platform.isMacOS) {
    cjk.addAll(
      existing([
        '/System/Library/Fonts/ヒラギノ角ゴシック W3.ttc',
        '/System/Library/Fonts/ヒラギノ角ゴシック W6.ttc',
      ]),
    );
    emoji.addAll(existing(['/System/Library/Fonts/Apple Color Emoji.ttc']));
  } else if (Platform.isLinux) {
    final home = Platform.environment['HOME'];
    for (final dir in [
      '/usr/share/fonts',
      '/usr/local/share/fonts',
      if (home != null) '$home/.local/share/fonts',
      if (home != null) '$home/.fonts',
    ]) {
      for (final file in files(dir)) {
        final n = file.path.split(Platform.pathSeparator).last;
        if ((n.startsWith('NotoSansCJK') || n.startsWith('NotoSansJP')) &&
            (n.contains('Regular') || n.contains('Bold'))) {
          cjk.add(file);
        } else if (n == 'NotoColorEmoji.ttf') {
          emoji.add(file);
        }
      }
    }
  } else if (Platform.isWindows) {
    final fonts = '${Platform.environment['WINDIR'] ?? r'C:\Windows'}\\Fonts';
    cjk.addAll(existing(['$fonts\\YuGothR.ttc', '$fonts\\YuGothB.ttc']));
    emoji.addAll(existing(['$fonts\\seguiemj.ttf']));
  }
  return {
    if (cjk.isNotEmpty) 'ShutterFallbackCjk': cjk,
    if (emoji.isNotEmpty) 'ShutterFallbackEmoji': emoji,
  };
}

/// google_fonts resolves a font from assets, then a path_provider cache,
/// then HTTP. Cached files are served as assets so it resolves them on
/// microtasks before the first frame. path_provider is answered with null
/// so that a font missing from the cache fails inside the capture (flutter
/// test's HTTP mock answers 400) instead of after it; the failure names
/// the font's URL, which the CLI downloads before shooting again.
void _prepareGoogleFonts(List<ShutterFont> fonts) {
  final messenger =
      TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger;
  messenger.setMockMethodCallHandler(
    const MethodChannel('plugins.flutter.io/path_provider'),
    (call) async => null,
  );
  final assetDir = Platform.environment['UNIT_TEST_ASSETS'];
  final appName = Platform.environment['APP_NAME'];
  if (fonts.isEmpty || assetDir == null || appName == null) return;
  final served = {
    for (final font in fonts) 'shutter_fonts/${font.asset}': font.path,
  };
  final prefix = 'packages/$appName/';
  // flutter_test's own `flutter/assets` handler, plus the cached fonts.
  messenger.setMockMessageHandler('flutter/assets', (message) {
    var key = utf8.decode(message!.buffer.asUint8List());
    if (served[key] case final path?) {
      return SynchronousFuture<ByteData>(
        ByteData.sublistView(File(path).readAsBytesSync()),
      );
    }
    var asset = File('$assetDir/$key');
    if (!asset.existsSync()) {
      if (!key.startsWith(prefix)) return null;
      key = key.replaceFirst(prefix, '');
      asset = File('$assetDir/$key');
      if (!asset.existsSync()) return null;
    }
    final bytes = ByteData.sublistView(asset.readAsBytesSync());
    if (key != 'AssetManifest.bin') return SynchronousFuture<ByteData>(bytes);
    const codec = StandardMessageCodec();
    final manifest = codec.decodeMessage(bytes);
    return SynchronousFuture<ByteData>(
      codec.encodeMessage({
        if (manifest is Map<Object?, Object?>) ...manifest,
        for (final key in served.keys)
          key: [
            {'asset': key},
          ],
      })!,
    );
  });
}

Future<void> _loadFonts(String materialFontsDir, List<ShutterFont> fonts) async {
  Future<ByteData> readFile(File file) async =>
      ByteData.sublistView(await file.readAsBytes());
  final manifest = jsonDecode(await rootBundle.loadString('FontManifest.json'))
      as List<Object?>;
  final families = <String, List<Future<ByteData>>>{};
  for (final family in manifest.cast<Map<String, Object?>>()) {
    final fonts = family['fonts']! as List<Object?>;
    families[family['family']! as String] = [
      for (final font in fonts.cast<Map<String, Object?>>())
        rootBundle.load(font['asset']! as String),
    ];
  }
  final dir = Directory(materialFontsDir);
  if (dir.existsSync()) {
    final files = dir.listSync().whereType<File>();
    final roboto = [
      for (final file in files)
        if (file.uri.pathSegments.last.startsWith('Roboto-') &&
            file.path.endsWith('.ttf'))
          file,
    ];
    families['Roboto'] = [for (final file in roboto) readFile(file)];
    // Cupertino text names the platform's system font through these
    // families, and the test engine resolves no system font. As a macOS
    // app does, they get SF Pro from the host, which is what iOS draws;
    // elsewhere Roboto, the Android system font.
    final sf = [
      for (final name in const ['SFNS.ttf', 'SFNSItalic.ttf'])
        if (Platform.isMacOS && File('/System/Library/Fonts/$name').existsSync())
          File('/System/Library/Fonts/$name'),
    ];
    final system = sf.isEmpty ? roboto : sf;
    for (final family in const ['CupertinoSystemText', 'CupertinoSystemDisplay']) {
      families.putIfAbsent(family, () => [for (final file in system) readFile(file)]);
    }
    families.putIfAbsent('MaterialIcons', () => [
      for (final file in files)
        if (file.uri.pathSegments.last.startsWith('MaterialIcons'))
          readFile(file),
    ]);
  }
  // Registered up front: a google_fonts style created during a frame
  // registers its font after that frame's layout, too late for capture.
  for (final font in fonts) {
    families[font.family] = [readFile(File(font.path))];
  }
  for (final MapEntry(key: family, value: files)
      in _systemFallbackFonts().entries) {
    families[family] = [for (final file in files) readFile(file)];
    _fallbackFamilies.add(family);
  }
  await Future.wait([
    for (final MapEntry(key: family, value: fonts) in families.entries)
      fonts.fold(FontLoader(family), (loader, font) => loader..addFont(font))
          .load(),
  ]);
}
''';
